# Generated by Django 4.1.3 on 2022-11-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('took', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my',
            old_name='message',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='my',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='my',
            name='name',
        ),
    ]
